name: Main MERN Azure App Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch: # Add this line to enable manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    # For the backend workflow
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: ./backend

    # For the frontend workflow
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: ./frontend

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18 # Adjust to the version used in your project

    - name: Install dependencies and Build React App
      run: |
        npm install
        npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: mern-azure-app-jg
