name: Main MERN Azure App Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch: # Add this line to enable manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # For the backend workflow
      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      # For the frontend workflow
      - name: Install frontend dependencies and Build React App
        run: |
          cd frontend
          npm install
          npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: mern-azure-app-jg
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
